apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uporabljajfacebook
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: uporabljajfacebook
    newName: rg.fr-par.scw.cloud/djnd/uporabljajfacebook
    newTag: '2e1a4c3a56d0291edf504f26e67aa5b0872df2d0'
